# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: slack-webhook-integration # NOTE: update this with your service name

custom:
  stage:  ${opt:stage, self:provider.stage}
  logRetentionInDays:
    dev: "14"          # stage[dev]は14日
    prod: "90"         # stage[prod]は90日
    default: "3"       # stageが見つからなかったらこれにfallbackするために設定

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 300
  memorySize: 512

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:GetFunction"
        - "lambda:ListFunctions"
      Resource: "arn:aws:lambda:*"

# you can define service wide environment variables here
  environment:
    STAGE: ${self:custom.stage}
    SLACK_OUTGOING_TOKEN: '__SLACK_OUTGOING_TOKEN_HERE__'

# you can add packaging information here
package:
  include:
    - config/**
    - lib/**
    - node_modules/**
  exclude:
    - .git/**
    - .gitignore
    - .envrc
    - .eslintrc
    - package.json
    - packega-lock.json

functions:
  receiveWebhook:
    handler: handler.receiveWebhook
    events:
      - http:
          path: slack/webhook
          method: post

# you can add CloudFormation resource templates here
resources:
  Resources:
    ReceiveWebhookLogGroup:
      Properties:
        RetentionInDays: ${self:custom.logRetentionInDays.${self:custom.stage}, self:custom.logRetentionInDays.default}
